version: "3.7"
services:
  # PHP CLI
  php-cli:
    container_name: php-cli
    restart: always
    tty: true
    working_dir: /var/www/app
    build: .
    volumes:
      - .:/var/www/app
      - /var/www/app/vendor
